function mostrarInformacao(secao) {
    var informacoes = {
        historia: 'Um gato siamês "vira-lata" é frequentemente um gato doméstico com características semelhantes aos siameses puros, mas sem um pedigree. Esses gatos podem ter o distintivo pelo colorpoint e olhos azuis dos siameses, mas como não são de raça pura, podem exibir uma variedade maior em termos de características físicas e comportamentais. Eles são resultado de cruzamentos naturais e não planejados e, no Brasil, como em muitos países, gatos com aparência siamesa podem ser encontrados em abrigos ou como animais de estimação adotados. Gatos vira-latas, também conhecidos como gatos sem raça definida (SRD), são extremamente comuns no Brasil e em muitos outros países. Eles surgem a partir da miscigenação natural entre diferentes raças de gatos, o que resulta em uma grande diversidade de aparências e comportamentos. No Brasil, esses gatos estão presentes em todas as regiões e são frequentemente encontrados vivendo nas ruas ou sendo cuidados por famílias como animais de estimação. A história dos gatos vira-latas é, em muitos aspectos, a história da própria sobrevivência e adaptabilidade dos gatos como espécie. Eles são uma parte importante do ecossistema urbano e muitas vezes desempenham um papel na controle da população de roedores. Com o crescente movimento de adoção e cuidados aos animais de rua, esses gatos têm ganhado mais atenção e cuidados, incluindo campanhas de castração e programas de adoção para garantir que eles tenham uma vida mais saudável e segura.        ',
        comportamento: 'Gatos normalmente são animais muitoO temperamento dos gatos Siameses é conhecido por ser bastante variável. Em geral, eles são gatos calmos, carinhosos e leais aos seus donos. No entanto, eles também podem ter momentos em que se tornam mais reservados e distantes, comportando-se de maneira mais quieta e apática. Essa raça é conhecida por sua independência, mas isso não significa que eles não precisem de interação. Na verdade, é importante que os gatos Siameses sejam socializados desde cedo para evitar que desenvolvam ciúmes em relação aos seus donos e para que possam conviver harmoniosamente com outras pessoas que fazem parte do seu ambiente. Os gatos Siameses são uma das raças de gatos pequenos mais reconhecidas e populares. Eles têm um tamanho que varia entre **20 a 30 cm** de altura e um peso que oscila entre **4 a 6 kg**. Essas características os tornam bastante adaptáveis a diferentes tipos de lares e estilos de vida. independentes...',
        cuidados: 'Claro, aqui está um resumo dos cuidados com um gato doméstico: 1. **Saúde**: Mantenha as vacinas em dia e visite o veterinário regularmente. 2. **Educação**: Ensine o uso da caixa de areia e do arranhador. 3. **Higiene**: Escove o pelo e limpe a caixa de areia frequentemente. 4. **Alimentação**: Ofereça uma dieta balanceada e adequada. 5. **Atividades**: Brinque e proporcione exercícios. 6. **Espaço**: Dê liberdade e um ambiente seguro. 7. **Unhas**: Corte as unhas quando necessário. 8. **Descanso**: Providencie uma cama confortável. 9. **Banho**: Banhos ocasionais podem ser necessários. Lembre-se de observar o comportamento do seu gato e consultar um veterinário para atender às necessidades individuais do seu pet.'
    };

    var divInformacoes = document.getElementById('informacoes');
    divInformacoes.innerHTML = '<p>' + informacoes[secao] + '</p>';
}
